export const GET_ALL_COIN_MARKET = 'GET_ALL_COIN_MARKET';
export const GET_ALL_COIN_MARKET_SUCCESS = 'GET_ALL_COIN_MARKET_SUCCESS';
export const GET_ALL_COIN_MARKET_ERROR = 'GET_ALL_COIN_MARKET_ERROR';
